//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColetorAlerta
    {
        public int Id { get; set; }
        public int Id_Empresa { get; set; }
        public int Id_Coletor { get; set; }
        public int Id_TipoAlerta { get; set; }
        public Nullable<int> Prioridade { get; set; }
        public string Descricao { get; set; }
        public string Email { get; set; }
        public Nullable<int> Regra { get; set; }
        public string Valor { get; set; }
        public Nullable<int> Ativo { get; set; }
    
        public virtual Coletor Coletor { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual ColetorTipoAlerta ColetorTipoAlerta { get; set; }
    }
}
