//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColetorAlertaLog
    {
        public int Id { get; set; }
        public int Id_Coletor { get; set; }
        public int Id_ColetorAlerta { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public string ValorRegra { get; set; }
        public string ValorEnviado { get; set; }
    }
}
