//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColetorTopico
    {
        public ColetorTopico()
        {
            this.ColetorTopicoLog = new HashSet<ColetorTopicoLog>();
        }
    
        public int Id { get; set; }
        public int Id_Coletor { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public Nullable<int> Ativo { get; set; }
    
        public virtual Coletor Coletor { get; set; }
        public virtual ICollection<ColetorTopicoLog> ColetorTopicoLog { get; set; }
    }
}
