//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColetorTipoAlerta
    {
        public ColetorTipoAlerta()
        {
            this.ColetorAlerta = new HashSet<ColetorAlerta>();
        }
    
        public int Id { get; set; }
        public int Id_Empresa { get; set; }
        public string Descricao { get; set; }
        public string UnidadeMedida { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> Tipo { get; set; }
    
        public virtual ICollection<ColetorAlerta> ColetorAlerta { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
