//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Coletor = new HashSet<Coletor>();
            this.ColetorAlerta = new HashSet<ColetorAlerta>();
            this.LogAtividade = new HashSet<LogAtividade>();
            this.Filial = new HashSet<Filial>();
            this.Gateway = new HashSet<Gateway>();
            this.Usuario = new HashSet<Usuario>();
            this.Maquina = new HashSet<Maquina>();
            this.ColetorTipoAlerta = new HashSet<ColetorTipoAlerta>();
            this.Programa = new HashSet<Programa>();
            this.Processo = new HashSet<Processo>();
            this.TipoProcesso = new HashSet<TipoProcesso>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Resumo { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Empresas { get; set; }
        public string URL { get; set; }
        public string AnalitycCode { get; set; }
        public string Site { get; set; }
        public string Endereco { get; set; }
        public string CEP { get; set; }
        public string Numero { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Telefone { get; set; }
        public string NomeFantasia { get; set; }
        public string Email { get; set; }
        public string Bairro { get; set; }
    
        public virtual ICollection<Coletor> Coletor { get; set; }
        public virtual ICollection<ColetorAlerta> ColetorAlerta { get; set; }
        public virtual ICollection<LogAtividade> LogAtividade { get; set; }
        public virtual ICollection<Filial> Filial { get; set; }
        public virtual ICollection<Gateway> Gateway { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual ICollection<Maquina> Maquina { get; set; }
        public virtual ICollection<ColetorTipoAlerta> ColetorTipoAlerta { get; set; }
        public virtual ICollection<Programa> Programa { get; set; }
        public virtual ICollection<Processo> Processo { get; set; }
        public virtual ICollection<TipoProcesso> TipoProcesso { get; set; }
    }
}
