//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaquinaLog
    {
        public int Id { get; set; }
        public int Id_Maquina { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public string DataHoraCLP { get; set; }
        public string Consumo { get; set; }
        public string NumeroCiclo { get; set; }
        public string TempoTrabalhando { get; set; }
        public string TempoParada { get; set; }
        public string TempoFalha { get; set; }
        public string Reserva1 { get; set; }
        public string Reserva2 { get; set; }
    
        public virtual Maquina Maquina { get; set; }
    }
}
