//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaquinaLogReport
    {
        public int Id { get; set; }
        public int Id_Maquina { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public string Tempo { get; set; }
        public string Kilos { get; set; }
        public string Passo { get; set; }
        public string Temperatura { get; set; }
        public string ProgramaExec { get; set; }
        public string RPM { get; set; }
        public string ProdutoA { get; set; }
        public string ProdutoB { get; set; }
        public string ProdutoC { get; set; }
        public string ProdutoD { get; set; }
        public string ProdutoE { get; set; }
        public string ProdutoF { get; set; }
        public string ProdutoG { get; set; }
    
        public virtual Maquina Maquina { get; set; }
    }
}
