//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processo
    {
        public Processo()
        {
            this.Programa = new HashSet<Programa>();
        }
    
        public int ID { get; set; }
        public int Id_Empresa { get; set; }
        public int Id_TipoProcesso { get; set; }
        public string Descricao { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Programa> Programa { get; set; }
        public virtual TipoProcesso TipoProcesso { get; set; }
    }
}
