//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceitaPassoCentrifugacao
    {
        public int Id { get; set; }
        public int Id_Receita { get; set; }
        public string ModoTrabalho { get; set; }
        public string Saida { get; set; }
        public string Velocidade1 { get; set; }
        public string Tempo1 { get; set; }
        public string Velocidade2 { get; set; }
        public string Tempo2 { get; set; }
        public string Velocidade3 { get; set; }
        public string Tempo3 { get; set; }
        public string Velocidade4 { get; set; }
        public string Tempo4 { get; set; }
        public string Velocidade5 { get; set; }
        public string Tempo5 { get; set; }
        public Nullable<int> Ativo { get; set; }
    
        public virtual Receita Receita { get; set; }
    }
}
