//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceitaPassoLavagem
    {
        public int Id { get; set; }
        public int Id_ReceitaPasso { get; set; }
        public string TempoOperacao { get; set; }
        public string TempoReversao { get; set; }
        public string RPM { get; set; }
        public string Temperatura { get; set; }
        public string SemVapor { get; set; }
        public string Entrada { get; set; }
        public string Nivel { get; set; }
        public string Saida { get; set; }
        public string ProdutoA { get; set; }
        public string ProdutoB { get; set; }
        public string ProdutoC { get; set; }
        public string ProdutoD { get; set; }
        public string ProdutoE { get; set; }
        public string ProdutoF { get; set; }
        public string ProdutoG { get; set; }
    
        public virtual ReceitaPasso ReceitaPasso { get; set; }
    }
}
