//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.UsuarioLogin = new HashSet<UsuarioLogin>();
        }
    
        public int ID { get; set; }
        public int Id_Empresa { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> Last { get; set; }
        public Nullable<System.DateTime> Create { get; set; }
        public Nullable<int> Ative { get; set; }
        public string Hash { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Tipo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<UsuarioLogin> UsuarioLogin { get; set; }
    }
}
